GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsIm5hbWUiOiJmYXRpaCIsImVtYWlsIjoiZmF0aWgxMjNAZ21haWwuY29tIiwiaWF0IjoxNzQ2MDc5NDYwLCJleHAiOjE3NDYwNzk0NzV9.3LT1gdW8jiHCqqGjt54znIe9jAo7KcY4EygsuaBT00M

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password": "12345678",
    "confPassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"fatih123@gmail.com",
    "password":"123"
}

###
GET http://localhost:5000/token


####

//API PENYAKIT

GET http://localhost:5000/penyakit