GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOiJhZG1pbiIsImlhdCI6MTc0Njg2NTA1MSwiZXhwIjoxNzQ2ODY1MDcxfQ.oA8NMYgykWJox5lR1nELTiHTvQu-5L2QjYIz2BcSIXU

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password": "12345678",
    "confPassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345678"
}

###
GET http://localhost:5000/token


####

//API PENYAKIT

GET http://localhost:5000/penyakit